import React from 'react';
import { FileDown, Printer, CheckCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { Modal } from '../common/Modal';
import { Button } from '../common/Button';

export const PDFPreviewModal = ({ isOpen, onClose, reportData }) => {
  if (!reportData) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Executive PDF Financial Report Preview" maxWidth="max-w-3xl">
      <div className="space-y-6">
        {/* Printable Document Container */}
        <div id="printable-report" className="bg-slate-950 border border-slate-800 p-8 rounded-2xl space-y-6 light:bg-white light:border-slate-300">
          {/* Document Header */}
          <div className="flex items-center justify-between border-b border-slate-800 pb-6 light:border-slate-300">
            <div>
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-600 via-purple-600 to-emerald-500 flex items-center justify-center text-white font-bold text-xs">
                  UPIQ
                </div>
                <h2 className="text-xl font-black text-slate-100 light:text-slate-900 tracking-tight">
                  UPIQ AI FINANCIAL STATEMENT
                </h2>
              </div>
              <p className="text-xs text-slate-400 mt-1">Period: {reportData.month}</p>
            </div>
            <div className="text-right">
              <span className="text-xs text-emerald-400 font-bold px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20">
                Health Score: {reportData.healthScore}/100
              </span>
              <p className="text-[10px] text-slate-500 mt-1">Generated by UPIQ Pro Engine</p>
            </div>
          </div>

          {/* KPI Matrix */}
          <div className="grid grid-cols-4 gap-4 text-xs">
            <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 light:bg-slate-100 light:border-slate-200">
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Total Revenue</span>
              <span className="text-sm font-extrabold text-emerald-400">
                ${reportData.totalIncome?.toLocaleString()}
              </span>
            </div>
            <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 light:bg-slate-100 light:border-slate-200">
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Total Expenses</span>
              <span className="text-sm font-extrabold text-rose-400">
                ${reportData.totalExpense?.toLocaleString()}
              </span>
            </div>
            <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 light:bg-slate-100 light:border-slate-200">
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Net Savings</span>
              <span className="text-sm font-extrabold text-indigo-400">
                ${reportData.netSavings?.toLocaleString()}
              </span>
            </div>
            <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 light:bg-slate-100 light:border-slate-200">
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Savings Rate</span>
              <span className="text-sm font-extrabold text-purple-400">
                {reportData.savingsRate}
              </span>
            </div>
          </div>

          {/* AI Executive Commentary */}
          <div className="bg-indigo-950/30 p-5 rounded-xl border border-indigo-500/20 space-y-2 text-xs">
            <h4 className="font-bold text-indigo-300 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-400" /> Executive AI Commentary
            </h4>
            <p className="text-slate-300 leading-relaxed">
              During {reportData.month}, net savings reached **${reportData.netSavings?.toLocaleString()}**, representing a savings rate of **{reportData.savingsRate}**. Major expenditure went towards **{reportData.topCategory}**. {reportData.fraudPrevented} fraudulent attempt was auto-intercepted by UPIQ Risk Engine with 0% data leakage.
            </p>
          </div>

          {/* Verification stamp */}
          <div className="flex items-center justify-between text-[11px] text-slate-500 pt-4 border-t border-slate-800 light:border-slate-200">
            <div className="flex items-center gap-1.5 text-emerald-400">
              <ShieldCheck className="w-4 h-4" /> Cryptographically Verified Statement
            </div>
            <span>Document ID: DOC-{reportData.id?.toUpperCase()}</span>
          </div>
        </div>

        {/* Action bar */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <Button onClick={onClose} variant="secondary">
            Close
          </Button>
          <Button onClick={handlePrint} variant="primary" icon={Printer}>
            Print / Save as PDF
          </Button>
        </div>
      </div>
    </Modal>
  );
};
