import api from './api';

export const BACKEND_FEATURES = [
  {
    id: 'auth',
    name: 'JWT Authentication & Role-Based Access',
    category: 'Core Security',
    status: 'ONLINE',
    endpoint: '/auth/login',
    description: 'Stateless user authentication, registration, and role-based permissions (Admin vs User).',
    badgeText: 'Active',
    icon: 'ShieldCheck',
  },
  {
    id: 'transactions',
    name: 'Transaction Engine & Ledger CRUD',
    category: 'Core Accounting',
    status: 'ONLINE',
    endpoint: '/transactions',
    description: 'Real-time transaction creation, reading, filtering, updates, and bulk delete actions.',
    badgeText: 'Active',
    icon: 'Receipt',
  },
  {
    id: 'autoCategorization',
    name: 'Smart Auto-Categorization Engine',
    category: 'Fintech Engine',
    status: 'ONLINE',
    endpoint: '/transactions/categorize-uncategorized',
    description: 'Deterministic merchant and description pattern recognition with automatic category creation.',
    badgeText: 'Active',
    icon: 'BrainCircuit',
  },
  {
    id: 'pdfImport',
    name: 'PDF Statement Import Parser',
    category: 'Data Import',
    status: 'ONLINE',
    endpoint: '/pdf/upload',
    description: 'Apache PDFBox-powered text extraction, parsing amounts, dates, and previewing candidate items.',
    badgeText: 'Active',
    icon: 'FileText',
  },
  {
    id: 'pdfReport',
    name: 'Authenticated PDF Financial Reports',
    category: 'Reporting',
    status: 'ONLINE',
    endpoint: '/financial/report',
    description: 'Generates downloadable PDF statements with verified summaries, category totals, and top expenses.',
    badgeText: 'Active',
    icon: 'Download',
  },
  {
    id: 'aiAssistant',
    name: 'Financial Assistant (System C + Grounded Engine)',
    category: 'AI Engine',
    status: 'ONLINE',
    endpoint: '/financial-chat',
    description: 'Calculates financial intents deterministically and queries local Ollama LLM with verified context.',
    badgeText: 'Active',
    icon: 'Bot',
  },
  {
    id: 'multiCurrency',
    name: 'Global Multi-Currency Conversion Engine',
    category: 'Internationalization',
    status: 'ONLINE',
    endpoint: 'Client Engine',
    description: 'Real-time multi-currency formatting for INR (₹), USD ($), EUR (€), GBP (£), and JPY (¥).',
    badgeText: 'Active',
    icon: 'Globe',
  },
  {
    id: 'csvUpload',
    name: 'Browser CSV Statement Upload UI',
    category: 'Data Import',
    status: 'COMING_SOON',
    endpoint: '/pdf/upload (CSV Parser Ready)',
    description: 'Direct browser CSV file upload & parsing interface in addition to PDF statement parsing.',
    badgeText: 'Phase 2 Coming Soon',
    icon: 'FileSpreadsheet',
  },
  {
    id: 'gnnFraudModel',
    name: 'Graph Neural Network (GNN) Fraud Microservice',
    category: 'Security & ML',
    status: 'COMING_SOON',
    endpoint: '/admin/gnn-telemetry',
    description: 'Deep Graph Neural Network graph anomaly detection pipeline for complex multi-node transaction fraud.',
    badgeText: 'Phase 2 Coming Soon',
    icon: 'ShieldAlert',
  },
  {
    id: 'investmentAdviceAI',
    name: 'AI Portfolio & Wealth Optimization Engine',
    category: 'Wealth Tech',
    status: 'COMING_SOON',
    endpoint: '/investments/optimize',
    description: 'Predictive portfolio rebalancing and algorithmic asset allocation advice based on monthly savings.',
    badgeText: 'Phase 2 Coming Soon',
    icon: 'TrendingUp',
  },
  {
    id: 'cloudBudgetSync',
    name: 'Cross-Device Cloud Database Budget Sync',
    category: 'Core Accounting',
    status: 'COMING_SOON',
    endpoint: '/budgets/sync',
    description: 'Persisting monthly category budgets to backend database tables for multi-device sync.',
    badgeText: 'Phase 2 Coming Soon',
    icon: 'Cloud',
  },
  {
    id: 'voiceAssistant',
    name: 'Real-Time Voice AI Assistant Interface',
    category: 'AI Engine',
    status: 'COMING_SOON',
    endpoint: '/financial-chat/voice',
    description: 'Speech-to-text input and natural voice audio responses for hands-free financial management.',
    badgeText: 'Phase 2 Coming Soon',
    icon: 'Mic',
  },
  {
    id: 'pushNotifications',
    name: 'Server Webhook Push Notifications',
    category: 'Alert System',
    status: 'COMING_SOON',
    endpoint: '/notifications/stream',
    description: 'Real-time web push notifications for anomaly spikes, budget caps, and bill payment reminders.',
    badgeText: 'Phase 2 Coming Soon',
    icon: 'Bell',
  },
];

export const checkBackendHealth = async () => {
  try {
    const res = await api.get('/categories');
    return { connected: true, status: res.status };
  } catch (err) {
    return { connected: false, error: err.message };
  }
};
